### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by MosfetWall** [PureCypher/Runescape-Launcher#1]
Hello,

The following error is thrown upon execution : 
`AttributeError: module 'os' has no attribute 'startfile'`

OS : Linux

**Comment by PureCypher** [comment]
This is for windows 10. Linux has a different format which I haven't even thought of implementing right away

**Comment by anwar6953** [comment]
+1 to a Mac-compatible version.
I think if you implement it for Linux, it will work for Mac, too.

**Comment by PureCypher** [comment]
Should be working on both Linux and Mac OS

**Comment by anwar6953** [comment]
Thanks!
